#ifndef _YANJUN_TOKEN_H_
#define _YANJUN_TOKEN_H_
#include "yacclimits.h"
enum TERMINALS{
DEC_ID=TERM_BASE,ID,DEC_NUM,NUM,CHARACTER,LEFT_OP,RIGHT_OP,INC_OP,DEC_OP,PTR_OP,LE_OP,GE_OP,EQ_OP,NE_OP,AND_OP,OR_OP,MUL_ASSIGN,DIV_ASSIGN,MOD_ASSIGN,ADD_ASSIGN,SUB_ASSIGN,LEFT_ASSIGN,RIGHT_ASSIGN,AND_ASSIGN,XOR_ASSIGN,OR_ASSIGN,TYPE_NAME,INT,VOID,CHAR,CASE,DEFAULT,IF,ELSE,SWITCH,WHILE,DO,FOR,GOTO,CONTINUE,BREAK,RETURN,ASM_BLOCK,
};
#endif