#ifndef _LIMITS_H_
#define _LIMITS_H_

#define YYTEXT_MAX_LENGTH 256

#define REGEXPR_MAX_LENGTH 256
#define LEXACTION_MAX_LENGTH	256

#define SYMBOL_BASE 1
#define SYMBOL_LAST	0x7f
#define SYMBOL_CNT	(SYMBOL_LAST-SYMBOL_BASE+1)
#define SYMBOL_ALL_CNT	(SYMBOL_LAST+1)

#define TERMEOF		 (SYMBOL_LAST+1)
#define TERMEMPTY	 (SYMBOL_LAST+2)
#define TERMVIRTUAL	 (SYMBOL_LAST+3)

#define TERM_BASE	 (TERMVIRTUAL+1)
#define TERM_MAX_COUNT 128


#define NONTERM_BASE (TERM_BASE+TERM_MAX_COUNT)
#define NONTERM_MAX_COUNT 256

#define TOKENDEF_MAX_COUNT 256

#define STARTSTATE_NAME_LENGTH 100
#define STARTSTATE_MAX_COUNT 256


#define PARSESTACK_SIZE 256
#define RULEBODY_MAX_LENGTH 256

//#define EXCLUSIVESTARTSTATE_BASE 256
#endif